import { Project } from "@/types";

export const projects: Project[] = [
  {
    title: 'US-Based Lead Generation & CRM Platform',
    description: 'Automated lead generation and CRM system for Business Development teams with custom web scraping pipelines, browser automation, and Next.js management dashboard.',
    technologies: ['Express.js', 'Next.js', 'Playwright', 'Web Scraping', 'Node.js', 'Cron Jobs'],
    githubLink: 'https://github.com/SaurabhDantani',
    image: '/projects/e-commerce-website.png',
    category: 'CRM & Automation',
    metric: 'Lead Generation Pipeline',
    featured: true,
  },
  {
    title: 'US-Based Medical Credentialing & RCM Software',
    description: 'Healthcare backend services and revenue cycle management (RCM) platform featuring NestJS services, automated Playwright/Python bots, and Next.js analytics dashboard.',
    technologies: ['NestJS', 'Python', 'Playwright', 'Next.js', 'PostgreSQL', 'Automated Workflows'],
    githubLink: 'https://github.com/SaurabhDantani',
    image: 'https://github.com/SaurabhDantani/folio/blob/main/site.png?raw=true',
    category: 'Healthcare & RCM',
    metric: 'Automated Billing RCM',
    featured: true,
  },
  {
    title: 'Real-Time IPO Management System',
    description: 'High-frequency financial market data processing platform with low-latency WebSocket live updates, subscription triggers, and scheduled market cron jobs.',
    technologies: ['NestJS', 'Socket.IO', 'TypeScript', 'Cron Jobs', 'PostgreSQL'],
    githubLink: 'https://github.com/SaurabhDantani',
    image: '/projects/chat-app.png',
    category: 'Real-Time Systems',
    metric: 'Real-Time Market Sync',
    featured: true,
  },
  {
    title: 'Community Management Platform',
    description: 'Scalable community portal with RESTful APIs, complex user permission matrix, relational database architecture, and Redux Toolkit state management.',
    technologies: ['Node.js', 'Express', 'PostgreSQL', 'TypeORM', 'React', 'Redux Toolkit'],
    githubLink: 'https://github.com/SaurabhDantani',
    image: 'https://github.com/SaurabhDantani/card-manager-react/blob/main/Screenshot%20(7).png?raw=true',
    category: 'Full Stack Web',
    metric: 'Scalable REST APIs',
    featured: true,
  },
  {
    title: 'AI & GenAI Portfolio Engine',
    description: 'Modern developer portfolio with dark mode glassmorphism, Framer Motion animations, floating navigation, AI chatbot assistant, and automated contact notifications.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Nodemailer'],
    githubLink: 'https://github.com/SaurabhDantani/folio',
    image: 'https://github.com/SaurabhDantani/folio/blob/main/site.png?raw=true',
    category: 'AI & Web',
    metric: '100 Core Web Vitals',
    featured: false,
  },
];